language: node_js
node_js:
  - "12"
services:
  - docker

before_install:
  - yarn install

script:
  - npm run build:prod
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t mrrs878/blog:latest .
  - docker push mrrs878/blog:latest
