language: node_js
node_js:
- '12'
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_04674a2f3de9_key -iv $encrypted_04674a2f3de9_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- yarn install
script:
- npm run build:prod
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t mrrs878/blog:latest .
- docker push mrrs878/blog:latest
