export const ADD_COUNT = 'ADD_COUNT';
export type ADD_COUNT = typeof ADD_COUNT;
export const UPDATE_ARTICLE_INFO = 'UPDATE_ARTICLE_INFO';
export type UPDATE_ARTICLE_INFO = typeof UPDATE_ARTICLE_INFO;
export const UPDATE_TOTAL_WORD = 'UPDATE_TOTAL_WORD';
export type UPDATE_TOTAL_WORD = typeof UPDATE_TOTAL_WORD;
